name: SonarCloud analysis

on:
  push:
    branches: [ "*" ]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  java-version: 17

permissions:
  pull-requests: write

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

#      - name: AI Code Reviewer
#        uses: f-lab-dev/ai-codereviewer@main
#        with:
#          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_BOT }} # The GITHUB_TOKEN is there by default so you just need to keep it like it is and not necessarily need to add it as secret as it will throw an error. [More Details](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)
#          OPENAI_API_KEY: ${{ secrets.SECRET_GPT }}
#          OPENAI_API_MODEL: "gpt-4"
#          exclude: "**/*.json, **/*.md"

      - name: Set SonarCloud Project Key
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
          ORG_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)
          SONAR_PROJECT_KEY="${ORG_NAME}_${REPO_NAME}"
          echo "SONAR_PROJECT_KEY=$SONAR_PROJECT_KEY" >> $GITHUB_ENV

      - name: Create Sonar Gradle File
        run: |
          sed -i '1s/^/plugins { id \"org.sonarqube\" version \"4.4.1.3373\" }\n/' settings.gradle

      - name: Analyze
        run: ./gradlew sonar -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} -Dsonar.organization=f-lab-edu-1 -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{ secrets.SECRET_SONARQUBE }} -Dsonar.gradle.skipCompile=true
        env:
          SONAR_TOKEN: ${{ secrets.SECRET_SONARQUBE }}

#      - name: Analyze with SonarCloud
#        uses: SonarSource/sonarcloud-github-action@master
#        id: analyze-sonarcloud
#        continue-on-error: true
#        env:
#          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_BOT }}
#          SONAR_TOKEN: ${{ secrets.SECRET_SONARQUBE }}
#        with:
#          args:
#            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
#            -Dsonar.organization=f-lab-edu-1
#
#      - name: Check for Sonarcloud Failure
#        run: |
#          if echo "${{ steps.analyze-sonarcloud.outputs.script-output }}" | grep -q "You should use the SonarQube plugin"; then
#            exit 1
#          fi
