name: SonarCloud analysis

on:
  push:
    branches: [ "*" ]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  java-version: 17

permissions:
  pull-requests: write

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

#      - name: Set SonarCloud Project Key
#        run: |
#          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
#          ORG_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)
#          SONAR_PROJECT_KEY="${ORG_NAME}_${REPO_NAME}"
#          echo "SONAR_PROJECT_KEY=$SONAR_PROJECT_KEY" >> $GITHUB_ENV
#
#      - name: Analyze
#        run: ./gradlew sonar -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} -Dsonar.organization=f-lab-edu-1 -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{ secrets.SECRET_SONARQUBE }} -Dsonar.gradle.skipCompile=true
#        env:
#          SONAR_TOKEN: ${{ secrets.SECRET_SONARQUBE }}

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        id: analyze-sonarcloud
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB }}
          SONAR_TOKEN: ${{ secrets.SECRET_SONARQUBE }}
        with:
          args:
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.organization=f-lab-edu-1

      - name: Check for Sonarcloud Failure
        run: |
          if echo "${{ steps.analyze-sonarcloud.outputs.script-output }}" | grep -q "You should use the SonarQube plugin"; then
            exit 1
          fi
